name: Update Typedoc Workflow

on:
  push:
    branches:
      - main

jobs:
  makedocs:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout docs repo
          uses: actions/checkout@v3
          with:
            repository: near/near-sdk-js
            ref: "develop"

        - name: Generate Documentation
          run: |
            npm i -g pnpm
            pnpm install --no-frozen-lockfile
            cd ./packages/near-sdk-js/src
            npx typedoc index.ts --out ./typedocs
            ls 
         
        - name: Upload docs as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: typedocs
            path: ./typedocs/
