name: Update Typedoc Workflow

on:
  push:
    branches:
      - main

  
jobs:
  update-typedocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v2

      - name: Checkout near-sdk-js repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.source_repo }}

      - name: Install Dependencies
        run: |
          ls
          cd near-sdk/js packages/near-sdk-js
          npm i -g pnpm
          pnpm install

      - name: Build Typedocs
        run: |
          cd packages/near-sdk-js
          npx typedoc src --out js-docs

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: js-docs
          path: packages/near-sdk-js/js-docs
