name: Update Typedoc Workflow

on:
  push:
    branches:
      - main

jobs:
  makedocs:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout docs repo
          uses: actions/checkout@v3
          with:
            repository: near/near-sdk-js
            ref: "develop"

        - name: Generate Documentation
          run: |
            ls -a
            npm i pnpm  
            npx pnpm@7.0.0 install
            echo "#### changing folder" 
            cd ./packages/near-sdk-js/src
            echo '### launching typedoc'
            npx typedoc index.ts

        - name: Upload docs as Artifact
          uses: actions/upload-artifact@v3
          with:
            name: typedocs
            path: ./docs/
